#!/bin/bash
set -u

if [ $# = 1 ]
then
  HWTNO="$1"
else
  HWTNO="0"
fi

# run_meas

L_FK_MIN="0"
L_FK_MAX="29"
SCALE_FACTORS=(1.0 1.5 1.3 1.7)


# experiment binary
EXE="/__PATH__/__TO__/main_experiment.out"    # TODO set path to main_experiment.out
ODIR="measurements_out"                       # TODO set path to measurements output dir

[[ ! -f "${EXE}" ]] && echo "Error: Executable '${EXE}' does not exist." && exit 1


START=`date +"%Y.%m.%d:%H.%M.%S"`
echo "# start: ${START}"
CURR=`date +"d%Y_%m_%d_t%H_%M_%S"`

OF="meas_build_bnu_${CURR}"

PARAM_A="--hwtno ${HWTNO} --od ${ODIR} --of ${OF} -m build_bnu"
PARAM_K="--l_fk_min ${L_FK_MIN} --l_fk_max ${L_FK_MAX}"

echo "${PARAM_A} ${PARAM_K}"

for factor in "${SCALE_FACTORS[@]}"; do
  PARAM_X="--key_scale_factor=${factor} --fk_scale_factor=${factor}"
  echo "scale factors: ${PARAM_X}"
  ${EXE} ${PARAM_A} ${PARAM_K} ${PARAM_X} >> z_run_meas_build_bnu_${OF}.prot
done

END=`date +"%Y.%m.%d:%H.%M.%S"`
echo "# start: ${START}, end: ${END}"

echo "# FIN"
